apiVersion: v2
name: cryoem-services
description: An umbrella Helm chart for EM processing services
version: 1.3.3
dependencies:
  - name: bfactor_setup
  - name: clem_align_and_merge
  - name: clem_process_raw_lifs
  - name: clem_process_raw_tiffs
  - name: cluster_submission
  - name: cryolo
  - name: cryolo_gpu
  - name: ctffind
  - name: denoise
  - name: denoise_slurm
  - name: extract
  - name: extract_class
  - name: icebreaker
  - name: images
  - name: ispyb_connector
  - name: membrain_seg
  - name: motioncorr
  - name: node_creator
  - name: postprocess
  - name: process_recipe
  - name: select_classes
  - name: select_particles
  - name: tomo_align
  - name: tomo_align_slurm
